[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
tokio = { version = "1.38.0", features = ["full"] }
serde = {  version = "1.0.204", features = ["derive"] }
tokio-util = { version = "0.7.11", features = ["full"] }
futures = "0.3.30"
bytes = "1.6.0"
